on: [workflow_dispatch]
jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.0
      - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@main
      with:
        ndk-version: r21e
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - name: Install Haxelib
        run: |
          haxelib git hmm https://github.com/funkincrew/hmm
          haxelib run hmm install
        - name: Configure Android
      run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
      env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: |
          haxelib run lime build android
          haxelib run lime rebuild hxcpp
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
